### ISSUE TITLE
code modification, please read the following issue attentively you will understand what i am saying 

### ISSUE THREAD

**Issue by kiara-lens** [fonkamloic/UnionFind#1]
case 6:

                    printf("Enter amount of test data: "); //prompt for amount of data 
                    scanf("%d", &value); //reads amount of data
                    srand(0);
                    for(int i = 0 ; i < value ; i++){
                        value1 = rand() % value; //i modified this line of code to >> value1 = rand()% 10000
                        headList = insertNode(headList, value1);
                    }
so for an input set of 10 integers it will be = 2362, 41421,16649,60492,85386,38335,47793,36915,9277,30886

                    // partition half of the elements
                    for(int i = 0 ; i < value  ; i++ ){
      //This is where the real problem is  because for all the values of i value1=value2 = 2362 hence no partitioning occurs.
                        value1 = rand() % value;
                        value2 = rand() % value;
                        join(headList, value1, value2);
                    }

                    //print partitions
                    showSets(headList);
                    break;

**Comment by fonkamloic** [comment]
What I'm I reading?

**Comment by kiara-lens** [comment]
haven't you seen what is under?
